[project]
name = "swarmui-exif-to-civitai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "pillow>=11.3.0",
]
